services:
  hivemq-broker:
    image: hivemq/hivemq4
    ports:
      - "8080:8080" # HTTP Dashboard
      - "1883:1883" # MQTT Port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"] # Check HiveMQ Dashboard
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 10s

  python-app:
    build:
      context: ./app
    depends_on:
      hivemq-broker:
        condition: service_healthy
    environment:
      - HIVEMQ_HOST=hivemq-broker
      - HIVEMQ_PORT=1883
      - TZ=Europe/Brussels
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
